CREATE TABLE company_stock (
 
`STOCK_CODE` INT(20) NOT NULL,
 
`COMPANY_CODE` INT(20) NOT NULL,
 
`STOCK_PRICE` BIGINT(250) DEFAULT NULL,
 
`STOCK_UPDATED_DT` DATE DEFAULT NULL,
 
`STOCK_UPDATED_TS` VARCHAR(250) NULL DEFAULT NULL,
 
PRIMARY KEY (STOCK_CODE),

FOREIGN KEY (COMPANY_CODE) REFERENCES company(COMPANY_CODE)
)