CREATE TABLE company (
 
`COMPANY_CODE` INT(20)  NOT NULL,
 
`COMPANY_NAME` VARCHAR(250) NOT NULL,
 
`COMPANY_CEO` VARCHAR(250) NOT NULL,
 
`WEBSITE` VARCHAR(250) DEFAULT NULL,
 
`TURN_OVER` BIGINT(250) DEFAULT NULL,
 
`STOCK_PRICE` BIGINT(250) DEFAULT NULL,
 
`STOCK_UPDATED_DT` DATE DEFAULT NULL,
 
`STOCK_UPDATED_TS` VARCHAR(250) NULL DEFAULT NULL,
 
PRIMARY KEY (COMPANY_CODE)
)